Repository magnars/dash.el, pull requests merged in 2021-01, with the labels that each got.

#354 Improve take/drop definitions
  README.md
  dash.el
  dash.info
  dash.texi
  dev/examples.el
Labels: bug, discussion, enhancement

#355 Remove generated manual dash.info
  create-docs.sh
  dash.info
Labels: documentation, enhancement

#358 Various Texinfo manual improvements
  .gitignore
  dash-template.texi
  dash.texi
  dev/examples-to-info.el
  doc/fdl.texi
  doc/gpl.texi
Labels: discussion, documentation, enhancement

#359 Add Makefile
  .github/workflows/test.yml
  Makefile
  README.md
  create-docs.sh
  dash-template.texi
  dash.texi
  dev/examples.el
  pre-commit.sh
  readme-template.md
  run-tests.sh
Labels: enhancement

#314 Add anaphoric versions of -reductions et al.
  README.md
  dash.el
  dash.texi
  dev/examples.el
Labels: bug, enhancement

#364 Add info-lookup-symbol support
  README.md
  dash-template.texi
  dash.el
  dash.texi
  readme-template.md
Labels: documentation, enhancement

#235 Use lexical binding for -grade-up/down
  README.md
  dash.el
  dash.texi
  dev/examples.el
Labels: enhancement

#215 Add -iota (#207)
  dash.el
  dev/examples.el
Labels: enhancement

#363 Deprecate variadic -list
  README.md
  dash.el
  dash.texi
  dev/examples.el
Labels: enhancement

#366 Avoid evaluating file-local variables
  dash.el
  dev/examples.el
Labels: enhancement

#367 Fix handling nils of -some-->
  README.md
  dash.el
  dash.texi
  dev/examples.el
Labels: enhancement
